return {
  schemaVersion = 1,
  id = "ava-base-f18c",
  name = "AVA Base + F/A-18C Hornet Grip",
  controls = {
    { id = "ava-hornet-trigger-stage1", key = "JOY_BTN1", type = "button", hardwareLabel = "Trigger first stage" },
    { id = "ava-hornet-weapon-release", key = "JOY_BTN2", type = "button", hardwareLabel = "Weapons release" },
    { id = "ava-hornet-nws-undesignate", key = "JOY_BTN3", type = "button", hardwareLabel = "NWS / undesignate" },
    { id = "ava-hornet-paddle", key = "JOY_BTN4", type = "button", hardwareLabel = "AP / NWS disconnect" },
    { id = "ava-hornet-recce-event", key = "JOY_BTN5", type = "button", hardwareLabel = "Recce event" },
    { id = "ava-hornet-trigger-stage2", key = "JOY_BTN6", type = "button", hardwareLabel = "Trigger second stage" },
    { id = "ava-hornet-sensor-up", key = "JOY_BTN7", type = "hat-direction", hardwareLabel = "Sensor control up" },
    { id = "ava-hornet-sensor-right", key = "JOY_BTN8", type = "hat-direction", hardwareLabel = "Sensor control right" },
    { id = "ava-hornet-sensor-down", key = "JOY_BTN9", type = "hat-direction", hardwareLabel = "Sensor control down" },
    { id = "ava-hornet-sensor-left", key = "JOY_BTN10", type = "hat-direction", hardwareLabel = "Sensor control left" },
    { id = "ava-hornet-vr-up", key = "JOY_BTN11", type = "hat-direction", hardwareLabel = "VR reset up" },
    { id = "ava-hornet-vr-push", key = "JOY_BTN12", type = "button", hardwareLabel = "VR reset push" },
    { id = "ava-hornet-vr-down", key = "JOY_BTN13", type = "hat-direction", hardwareLabel = "VR reset down" },
    { id = "ava-hornet-sensor-push", key = "JOY_BTN14", type = "button", hardwareLabel = "Sensor control push" },
    { id = "ava-hornet-weapon-select-forward", key = "JOY_BTN15", type = "hat-direction", hardwareLabel = "Weapon select forward" },
    { id = "ava-hornet-weapon-select-right", key = "JOY_BTN16", type = "hat-direction", hardwareLabel = "Weapon select right" },
    { id = "ava-hornet-weapon-select-aft", key = "JOY_BTN17", type = "hat-direction", hardwareLabel = "Weapon select aft" },
    { id = "ava-hornet-weapon-select-left", key = "JOY_BTN18", type = "hat-direction", hardwareLabel = "Weapon select left" },
    { id = "ava-hornet-weapon-select-push", key = "JOY_BTN19", type = "button", hardwareLabel = "Weapon select push" },
    { id = "ava-hornet-trim-up", key = "JOY_POV1_U", type = "hat-direction", hardwareLabel = "Trim up" },
    { id = "ava-hornet-trim-up-right", key = "JOY_POV1_UR", type = "hat-direction", hardwareLabel = "Trim up-right" },
    { id = "ava-hornet-trim-right", key = "JOY_POV1_R", type = "hat-direction", hardwareLabel = "Trim right" },
    { id = "ava-hornet-trim-down-right", key = "JOY_POV1_DR", type = "hat-direction", hardwareLabel = "Trim down-right" },
    { id = "ava-hornet-trim-down", key = "JOY_POV1_D", type = "hat-direction", hardwareLabel = "Trim down" },
    { id = "ava-hornet-trim-down-left", key = "JOY_POV1_DL", type = "hat-direction", hardwareLabel = "Trim down-left" },
    { id = "ava-hornet-trim-left", key = "JOY_POV1_L", type = "hat-direction", hardwareLabel = "Trim left" },
    { id = "ava-hornet-trim-up-left", key = "JOY_POV1_UL", type = "hat-direction", hardwareLabel = "Trim up-left" },
    { id = "ava-hornet-roll-axis", key = "JOY_X", type = "axis", hardwareLabel = "Roll axis" },
    { id = "ava-hornet-pitch-axis", key = "JOY_Y", type = "axis", hardwareLabel = "Pitch axis" },
  },
}
