return {
  schemaVersion = 1,
  id = "tm-mfd",
  name = "TM MFD",
  variants = { "MFD1", "MFD2", "MFD3", "MFD4" },
  controls = {
    { id = "mfd-osb-t1", key = "JOY_BTN1", type = "button", hardwareLabel = "OSB01" },
    { id = "mfd-osb-t2", key = "JOY_BTN2", type = "button", hardwareLabel = "OSB02" },
    { id = "mfd-osb-t3", key = "JOY_BTN3", type = "button", hardwareLabel = "OSB03" },
    { id = "mfd-osb-t4", key = "JOY_BTN4", type = "button", hardwareLabel = "OSB04" },
    { id = "mfd-osb-t5", key = "JOY_BTN5", type = "button", hardwareLabel = "OSB05" },
    { id = "mfd-osb-r1", key = "JOY_BTN6", type = "button", hardwareLabel = "OSB06" },
    { id = "mfd-osb-r2", key = "JOY_BTN7", type = "button", hardwareLabel = "OSB07" },
    { id = "mfd-osb-r3", key = "JOY_BTN8", type = "button", hardwareLabel = "OSB08" },
    { id = "mfd-osb-r4", key = "JOY_BTN9", type = "button", hardwareLabel = "OSB09" },
    { id = "mfd-osb-r5", key = "JOY_BTN10", type = "button", hardwareLabel = "OSB10" },
    { id = "mfd-osb-b5", key = "JOY_BTN11", type = "button", hardwareLabel = "OSB11" },
    { id = "mfd-osb-b4", key = "JOY_BTN12", type = "button", hardwareLabel = "OSB12" },
    { id = "mfd-osb-b3", key = "JOY_BTN13", type = "button", hardwareLabel = "OSB13" },
    { id = "mfd-osb-b2", key = "JOY_BTN14", type = "button", hardwareLabel = "OSB14" },
    { id = "mfd-osb-b1", key = "JOY_BTN15", type = "button", hardwareLabel = "OSB15" },
    { id = "mfd-osb-l5", key = "JOY_BTN16", type = "button", hardwareLabel = "OSB16" },
    { id = "mfd-osb-l4", key = "JOY_BTN17", type = "button", hardwareLabel = "OSB17" },
    { id = "mfd-osb-l3", key = "JOY_BTN18", type = "button", hardwareLabel = "OSB18" },
    { id = "mfd-osb-l2", key = "JOY_BTN19", type = "button", hardwareLabel = "OSB19" },
    { id = "mfd-osb-l1", key = "JOY_BTN20", type = "button", hardwareLabel = "OSB20" },
    { id = "mfd-rocker-gain", key = "JOY_BTN27", type = "rocker-position", hardwareLabel = "GAIN up", group = "gain-level", position = "up" },
    { id = "mfd-rocker-lvl", key = "JOY_BTN28", type = "rocker-position", hardwareLabel = "LVL down", group = "gain-level", position = "down" },
    { id = "mfd-rocker-con-up", key = "JOY_BTN23", type = "rocker-position", hardwareLabel = "CON up", group = "contrast", position = "up" },
    { id = "mfd-rocker-con-down", key = "JOY_BTN24", type = "rocker-position", hardwareLabel = "CON down", group = "contrast", position = "down" },
    { id = "mfd-rocker-brt-up", key = "JOY_BTN25", type = "rocker-position", hardwareLabel = "BRT up", group = "brightness", position = "up" },
    { id = "mfd-rocker-brt-down", key = "JOY_BTN26", type = "rocker-position", hardwareLabel = "BRT down", group = "brightness", position = "down" },
    { id = "mfd-rocker-sym", key = "JOY_BTN21", type = "rocker-position", hardwareLabel = "SYM up", group = "symbol-intensity", position = "up" },
    { id = "mfd-rocker-int", key = "JOY_BTN22", type = "rocker-position", hardwareLabel = "INT down", group = "symbol-intensity", position = "down" },
  },
}
