return {
  schemaVersion = 1,
  id = "tm-warthog-throttle",
  name = "TM Warthog Throttle",
  controls = {
    { id = "warthog-thr-slew-push", key = "JOY_BTN1", type = "button", hardwareLabel = "Slew push" },
    { id = "warthog-thr-mic-up", key = "JOY_BTN2", type = "hat-direction", hardwareLabel = "MIC up" },
    { id = "warthog-thr-mic-right", key = "JOY_BTN3", type = "hat-direction", hardwareLabel = "MIC right" },
    { id = "warthog-thr-mic-down", key = "JOY_BTN4", type = "hat-direction", hardwareLabel = "MIC down" },
    { id = "warthog-thr-mic-left", key = "JOY_BTN5", type = "hat-direction", hardwareLabel = "MIC left" },
    { id = "warthog-thr-mic-push", key = "JOY_BTN6", type = "button", hardwareLabel = "MIC push" },
    { id = "warthog-thr-speedbrake-forward", key = "JOY_BTN7", type = "switch-position", hardwareLabel = "Speedbrake forward" },
    { id = "warthog-thr-speedbrake-back", key = "JOY_BTN8", type = "switch-position", hardwareLabel = "Speedbrake back" },
    { id = "warthog-thr-boat-forward", key = "JOY_BTN9", type = "switch-position", hardwareLabel = "Boat forward" },
    { id = "warthog-thr-boat-back", key = "JOY_BTN10", type = "switch-position", hardwareLabel = "Boat back" },
    { id = "warthog-thr-china-forward", key = "JOY_BTN11", type = "switch-position", hardwareLabel = "China forward" },
    { id = "warthog-thr-china-back", key = "JOY_BTN12", type = "switch-position", hardwareLabel = "China back" },
    { id = "warthog-thr-pinky-forward", key = "JOY_BTN13", type = "switch-position", hardwareLabel = "Pinky forward" },
    { id = "warthog-thr-pinky-back", key = "JOY_BTN14", type = "switch-position", hardwareLabel = "Pinky back" },
    { id = "warthog-thr-left-throttle-button", key = "JOY_BTN15", type = "button", hardwareLabel = "Left throttle button" },
    { id = "warthog-thr-fuel-flow-left", key = "JOY_BTN16", type = "switch-position", hardwareLabel = "Fuel flow left" },
    { id = "warthog-thr-fuel-flow-right", key = "JOY_BTN17", type = "switch-position", hardwareLabel = "Fuel flow right" },
    { id = "warthog-thr-engine-operate-left-down", key = "JOY_BTN18", type = "switch-position", hardwareLabel = "Engine operate left down" },
    { id = "warthog-thr-engine-operate-right-down", key = "JOY_BTN19", type = "switch-position", hardwareLabel = "Engine operate right down" },
    { id = "warthog-thr-apu-start", key = "JOY_BTN20", type = "switch-position", hardwareLabel = "APU start" },
    { id = "warthog-thr-landing-horn-silence", key = "JOY_BTN21", type = "button", hardwareLabel = "Landing horn silence" },
    { id = "warthog-thr-flaps-up", key = "JOY_BTN22", type = "switch-position", hardwareLabel = "Flaps up" },
    { id = "warthog-thr-flaps-down", key = "JOY_BTN23", type = "switch-position", hardwareLabel = "Flaps down" },
    { id = "warthog-thr-eac-on", key = "JOY_BTN24", type = "switch-position", hardwareLabel = "EAC on" },
    { id = "warthog-thr-rdr-alt-normal", key = "JOY_BTN25", type = "switch-position", hardwareLabel = "RDR ALT normal" },
    { id = "warthog-thr-ap-engage", key = "JOY_BTN26", type = "button", hardwareLabel = "Autopilot engage" },
    { id = "warthog-thr-ap-select-up", key = "JOY_BTN27", type = "switch-position", hardwareLabel = "Autopilot select up" },
    { id = "warthog-thr-ap-select-down", key = "JOY_BTN28", type = "switch-position", hardwareLabel = "Autopilot select down" },
    { id = "warthog-thr-left-engine-idle-off", key = "JOY_BTN29", type = "switch-position", hardwareLabel = "Left engine idle/off" },
    { id = "warthog-thr-right-engine-idle-off", key = "JOY_BTN30", type = "switch-position", hardwareLabel = "Right engine idle/off" },
    { id = "warthog-thr-engine-operate-left-up", key = "JOY_BTN31", type = "switch-position", hardwareLabel = "Engine operate left up" },
    { id = "warthog-thr-engine-operate-right-up", key = "JOY_BTN32", type = "switch-position", hardwareLabel = "Engine operate right up" },
    { id = "warthog-thr-coolie-up", key = "JOY_POV1_U", type = "hat-direction", hardwareLabel = "Coolie up" },
    { id = "warthog-thr-coolie-right", key = "JOY_POV1_R", type = "hat-direction", hardwareLabel = "Coolie right" },
    { id = "warthog-thr-coolie-down", key = "JOY_POV1_D", type = "hat-direction", hardwareLabel = "Coolie down" },
    { id = "warthog-thr-coolie-left", key = "JOY_POV1_L", type = "hat-direction", hardwareLabel = "Coolie left" },
    { id = "warthog-thr-axis-slew-x", key = "JOY_X", type = "axis", hardwareLabel = "Slew X axis" },
    { id = "warthog-thr-axis-slew-y", key = "JOY_Y", type = "axis", hardwareLabel = "Slew Y axis" },
    { id = "warthog-thr-axis-right-throttle", key = "JOY_Z", type = "axis", hardwareLabel = "Right throttle axis" },
    { id = "warthog-thr-axis-left-throttle", key = "JOY_RZ", type = "axis", hardwareLabel = "Left throttle axis" },
    { id = "warthog-thr-axis-friction", key = "JOY_SLIDER1", type = "axis", hardwareLabel = "Friction axis" },
  },
}
