return {
  schemaVersion = 1,
  id = "tm-warthog-grip",
  name = "TM Warthog Joystick",
  controls = {
    { id = "warthog-grip-stage1", key = "JOY_BTN1", type = "button", hardwareLabel = "Trigger first stage" },
    { id = "warthog-grip-btn-red", key = "JOY_BTN2", type = "button", hardwareLabel = "Weapon release" },
    { id = "warthog-grip-pinky", key = "JOY_BTN3", type = "button", hardwareLabel = "Pinky lever" },
    { id = "warthog-grip-paddle", key = "JOY_BTN4", type = "button", hardwareLabel = "Nosewheel steering" },
    { id = "warthog-grip-rear-btn", key = "JOY_BTN5", type = "button", hardwareLabel = "Master mode control" },
    { id = "warthog-grip-stage2", key = "JOY_BTN6", type = "button", hardwareLabel = "Trigger second stage" },
    { id = "warthog-grip-boat-sw", key = "JOY_BTN7", type = "hat-direction", hardwareLabel = "TMS up" },
    { id = "warthog-grip-boat-sw", key = "JOY_BTN8", type = "hat-direction", hardwareLabel = "TMS right" },
    { id = "warthog-grip-boat-sw", key = "JOY_BTN9", type = "hat-direction", hardwareLabel = "TMS down" },
    { id = "warthog-grip-boat-sw", key = "JOY_BTN10", type = "hat-direction", hardwareLabel = "TMS left" },
    { id = "warthog-grip-dcs-hat", key = "JOY_BTN11", type = "hat-direction", hardwareLabel = "DMS up" },
    { id = "warthog-grip-dcs-hat", key = "JOY_BTN12", type = "hat-direction", hardwareLabel = "DMS right" },
    { id = "warthog-grip-dcs-hat", key = "JOY_BTN13", type = "hat-direction", hardwareLabel = "DMS down" },
    { id = "warthog-grip-dcs-hat", key = "JOY_BTN14", type = "hat-direction", hardwareLabel = "DMS left" },
    { id = "warthog-grip-china-hat", key = "JOY_BTN15", type = "hat-direction", hardwareLabel = "CMS forward" },
    { id = "warthog-grip-china-hat", key = "JOY_BTN16", type = "hat-direction", hardwareLabel = "CMS right" },
    { id = "warthog-grip-china-hat", key = "JOY_BTN17", type = "hat-direction", hardwareLabel = "CMS aft" },
    { id = "warthog-grip-china-hat", key = "JOY_BTN18", type = "hat-direction", hardwareLabel = "CMS left" },
    { id = "warthog-grip-china-hat", key = "JOY_BTN19", type = "button", hardwareLabel = "CMS push" },
    { id = "warthog-grip-hat", key = "JOY_POV1_U", type = "hat-direction", hardwareLabel = "Trim up" },
    { id = "warthog-grip-hat", key = "JOY_POV1_R", type = "hat-direction", hardwareLabel = "Trim right" },
    { id = "warthog-grip-hat", key = "JOY_POV1_D", type = "hat-direction", hardwareLabel = "Trim down" },
    { id = "warthog-grip-hat", key = "JOY_POV1_L", type = "hat-direction", hardwareLabel = "Trim left" },
    { id = "warthog-grip-rear-sw1", key = "JOY_X", type = "axis", hardwareLabel = "Roll axis" },
    { id = "warthog-grip-rear-sw2", key = "JOY_Y", type = "axis", hardwareLabel = "Pitch axis" },
  },
}
