return {
  schemaVersion = 1,
  id = "tm-warthog-grip",
  name = "TM Warthog Joystick",
  controls = {
    { id = "warthog-grip-stage1", key = "JOY_BTN1", type = "button", hardwareLabel = "Trigger 1" },
    { id = "warthog-grip-btn-red", key = "JOY_BTN2", type = "button", hardwareLabel = "Pickle" },
    { id = "warthog-grip-pinky", key = "JOY_BTN4", type = "button", hardwareLabel = "Pinky lever" },
    { id = "warthog-grip-paddle", key = "JOY_BTN3", type = "button", hardwareLabel = "NWS / Shift" },
    { id = "warthog-grip-rear-btn", key = "JOY_BTN5", type = "button", hardwareLabel = "Master mode" },
    { id = "warthog-grip-stage2", key = "JOY_BTN6", type = "button", hardwareLabel = "Trigger 2" },
    { id = "warthog-grip-tms-up", key = "JOY_BTN7", type = "hat-direction", hardwareLabel = "TMS up" },
    { id = "warthog-grip-tms-right", key = "JOY_BTN8", type = "hat-direction", hardwareLabel = "TMS right" },
    { id = "warthog-grip-tms-down", key = "JOY_BTN9", type = "hat-direction", hardwareLabel = "TMS down" },
    { id = "warthog-grip-tms-left", key = "JOY_BTN10", type = "hat-direction", hardwareLabel = "TMS left" },
    { id = "warthog-grip-dms-up", key = "JOY_BTN11", type = "hat-direction", hardwareLabel = "DMS up" },
    { id = "warthog-grip-dms-right", key = "JOY_BTN12", type = "hat-direction", hardwareLabel = "DMS right" },
    { id = "warthog-grip-dms-down", key = "JOY_BTN13", type = "hat-direction", hardwareLabel = "DMS down" },
    { id = "warthog-grip-dms-left", key = "JOY_BTN14", type = "hat-direction", hardwareLabel = "DMS left" },
    { id = "warthog-grip-cms-forward", key = "JOY_BTN15", type = "hat-direction", hardwareLabel = "CMS forward" },
    { id = "warthog-grip-cms-right", key = "JOY_BTN16", type = "hat-direction", hardwareLabel = "CMS right" },
    { id = "warthog-grip-cms-aft", key = "JOY_BTN17", type = "hat-direction", hardwareLabel = "CMS aft" },
    { id = "warthog-grip-cms-left", key = "JOY_BTN18", type = "hat-direction", hardwareLabel = "CMS left" },
    { id = "warthog-grip-cms-push", key = "JOY_BTN19", type = "button", hardwareLabel = "CMS push" },
    { id = "warthog-grip-trim-up", key = "JOY_POV1_U", type = "hat-direction", hardwareLabel = "Trim up" },
    { id = "warthog-grip-trim-right", key = "JOY_POV1_R", type = "hat-direction", hardwareLabel = "Trim right" },
    { id = "warthog-grip-trim-down", key = "JOY_POV1_D", type = "hat-direction", hardwareLabel = "Trim down" },
    { id = "warthog-grip-trim-left", key = "JOY_POV1_L", type = "hat-direction", hardwareLabel = "Trim left" },
    { id = "warthog-grip-rear-sw1", key = "JOY_X", type = "axis", hardwareLabel = "Roll axis" },
    { id = "warthog-grip-rear-sw2", key = "JOY_Y", type = "axis", hardwareLabel = "Pitch axis" },
  },
}
