return {
  schemaVersion = 1,
  id = "viper-tqs-mission-pack",
  name = "Viper TQS + Mission Pack",
  controls = {
    { id = "viper-tqs-button-01", key = "JOY_BTN1", type = "button-position", hardwareLabel = "Button 1 — MIC IFF OUT (AutoHotkey)" },
    { id = "viper-tqs-button-02", key = "JOY_BTN2", type = "button-position", hardwareLabel = "Button 2 — MIC UHF (AutoHotkey)" },
    { id = "viper-tqs-button-03", key = "JOY_BTN3", type = "button-position", hardwareLabel = "Button 3 — MIC IFF IN (AutoHotkey)" },
    { id = "viper-tqs-button-04", key = "JOY_BTN4", type = "button-position", hardwareLabel = "Button 4 — MIC VHF (AutoHotkey)" },
    { id = "viper-tqs-button-05", key = "JOY_BTN5", type = "button-position", hardwareLabel = "Button 5 — MIC PRESS (AutoHotkey)" },
    { id = "viper-tqs-button-06", key = "JOY_BTN6", type = "button-position", hardwareLabel = "Button 6 — UNCAGE" },
    { id = "viper-tqs-button-07", key = "JOY_BTN7", type = "button-position", hardwareLabel = "Button 7 — DOGFIGHT" },
    { id = "viper-tqs-button-08", key = "JOY_BTN8", type = "button-position", hardwareLabel = "Button 8 — MISSILE OVERRIDE" },
    { id = "viper-tqs-button-09", key = "JOY_BTN9", type = "button-position", hardwareLabel = "Button 9 — SPD BRK EXTEND" },
    { id = "viper-tqs-button-10", key = "JOY_BTN10", type = "button-position", hardwareLabel = "Button 10 — SPD BRK RETRACT" },
    { id = "viper-tqs-button-11", key = "JOY_BTN11", type = "button-position", hardwareLabel = "Button 11 — Unassigned" },
    { id = "viper-tqs-button-12", key = "JOY_BTN12", type = "button-position", hardwareLabel = "Button 12 — ENABLE" },
    { id = "viper-tqs-button-13", key = "JOY_BTN13", type = "button-position", hardwareLabel = "Button 13 — DCS UP" },
    { id = "viper-tqs-button-14", key = "JOY_BTN14", type = "button-position", hardwareLabel = "Button 14 — DCS SEQ" },
    { id = "viper-tqs-button-15", key = "JOY_BTN15", type = "button-position", hardwareLabel = "Button 15 — DCS DOWN" },
    { id = "viper-tqs-button-16", key = "JOY_BTN16", type = "button-position", hardwareLabel = "Button 16 — DCS RET" },
    { id = "viper-tqs-button-17", key = "JOY_BTN17", type = "button-position", hardwareLabel = "Button 17 — CHAFF/FLARE" },
    { id = "viper-tqs-button-18", key = "JOY_BTN18", type = "button-position", hardwareLabel = "Button 18 — THROTTLE OFF/IDLE" },
    { id = "viper-tqs-button-19", key = "JOY_BTN19", type = "button-position", hardwareLabel = "Button 19 — Unassigned" },
    { id = "viper-tqs-button-22", key = "JOY_BTN22", type = "button-position", hardwareLabel = "Button 22 — EMER STORES JETT" },
    { id = "viper-tqs-button-23", key = "JOY_BTN23", type = "button-position", hardwareLabel = "Button 23 — MASTER ARM" },
    { id = "viper-tqs-button-24", key = "JOY_BTN24", type = "button-position", hardwareLabel = "Button 24 — SIMULATE" },
    { id = "viper-tqs-button-25", key = "JOY_BTN25", type = "button-position", hardwareLabel = "Button 25 — PROGRAM 1" },
    { id = "viper-tqs-button-26", key = "JOY_BTN26", type = "button-position", hardwareLabel = "Button 26 — PROGRAM 2" },
    { id = "viper-tqs-button-27", key = "JOY_BTN27", type = "button-position", hardwareLabel = "Button 27 — PROGRAM 3" },
    { id = "viper-tqs-button-28", key = "JOY_BTN28", type = "button-position", hardwareLabel = "Button 28 — PROGRAM 4" },
    { id = "viper-tqs-button-29", key = "JOY_BTN29", type = "button-position", hardwareLabel = "Button 29 — MODE STBY" },
    { id = "viper-tqs-button-30", key = "JOY_BTN30", type = "button-position", hardwareLabel = "Button 30 — MODE MAN" },
    { id = "viper-tqs-button-31", key = "JOY_BTN31", type = "button-position", hardwareLabel = "Button 31 — MODE SEMI" },
    { id = "viper-tqs-button-32", key = "JOY_BTN32", type = "button-position", hardwareLabel = "Button 32 — MODE AUTO" },
    { id = "viper-tqs-button-33", key = "JOY_BTN33", type = "button-position", hardwareLabel = "Button 33 — MODE BYP" },
    { id = "viper-tqs-button-34", key = "JOY_BTN34", type = "button-position", hardwareLabel = "Button 34 — RWR SEARCH" },
    { id = "viper-tqs-button-35", key = "JOY_BTN35", type = "button-position", hardwareLabel = "Button 35 — RWR ACT/PWR" },
    { id = "viper-tqs-button-36", key = "JOY_BTN36", type = "button-position", hardwareLabel = "Button 36 — RWR ALTITUDE" },
    { id = "viper-tqs-button-37", key = "JOY_BTN37", type = "button-position", hardwareLabel = "Button 37 — RWR POWER" },
    { id = "viper-tqs-button-38", key = "JOY_BTN38", type = "button-position", hardwareLabel = "Button 38 — LG HANDLE UP" },
    { id = "viper-tqs-button-39", key = "JOY_BTN39", type = "button-position", hardwareLabel = "Button 39 — EXT LT ALL" },
    { id = "viper-tqs-button-40", key = "JOY_BTN40", type = "button-position", hardwareLabel = "Button 40 — EXT LT FORM" },
    { id = "viper-tqs-button-41", key = "JOY_BTN41", type = "button-position", hardwareLabel = "Button 41 — EXT LT NORM" },
    { id = "viper-tqs-button-42", key = "JOY_BTN42", type = "button-position", hardwareLabel = "Button 42 — HDG CW" },
    { id = "viper-tqs-button-43", key = "JOY_BTN43", type = "button-position", hardwareLabel = "Button 43 — HDG CCW" },
    { id = "viper-tqs-button-44", key = "JOY_BTN44", type = "button-position", hardwareLabel = "Button 44 — HDG DEPRESS" },
    { id = "viper-tqs-button-45", key = "JOY_BTN45", type = "button-position", hardwareLabel = "Button 45 — STORES CAT I" },
    { id = "viper-tqs-button-46", key = "JOY_BTN46", type = "button-position", hardwareLabel = "Button 46 — RF NORM" },
    { id = "viper-tqs-button-47", key = "JOY_BTN47", type = "button-position", hardwareLabel = "Button 47 — RF SILENT" },
    { id = "viper-tqs-button-48", key = "JOY_BTN48", type = "button-position", hardwareLabel = "Button 48 — LASER ARM" },
    { id = "viper-tqs-button-49", key = "JOY_BTN49", type = "button-position", hardwareLabel = "Button 49 — JMR ON" },
    { id = "viper-tqs-button-50", key = "JOY_BTN50", type = "button-position", hardwareLabel = "Button 50 — AP ROLL HDG SEL" },
    { id = "viper-tqs-button-51", key = "JOY_BTN51", type = "button-position", hardwareLabel = "Button 51 — AP ROLL STRG SEL" },
    { id = "viper-tqs-button-52", key = "JOY_BTN52", type = "button-position", hardwareLabel = "Button 52 — AP PITCH ALT HOLD" },
    { id = "viper-tqs-button-53", key = "JOY_BTN53", type = "button-position", hardwareLabel = "Button 53 — AP PITCH ATT HOLD" },
    { id = "viper-tqs-button-54", key = "JOY_BTN54", type = "button-position", hardwareLabel = "Button 54 — Unassigned" },
    { id = "viper-tqs-button-55", key = "JOY_BTN55", type = "button-position", hardwareLabel = "Button 55 — PROGRAM BIT" },
    { id = "viper-tqs-button-56", key = "JOY_BTN56", type = "button-position", hardwareLabel = "Button 56 — MODE OFF" },
    { id = "viper-tqs-button-57", key = "JOY_BTN57", type = "button-position", hardwareLabel = "Button 57 — LG HANDLE DN" },
    { id = "viper-tqs-button-58", key = "JOY_BTN58", type = "button-position", hardwareLabel = "Button 58 — EXT LT OFF" },
    { id = "viper-tqs-button-59", key = "JOY_BTN59", type = "button-position", hardwareLabel = "Button 59 — STORES CAT III" },
    { id = "viper-tqs-button-60", key = "JOY_BTN60", type = "button-position", hardwareLabel = "Button 60 — Unassigned" },
    { id = "viper-tqs-button-61", key = "JOY_BTN61", type = "button-position", hardwareLabel = "Button 61 — LASER OFF" },
    { id = "viper-tqs-button-62", key = "JOY_BTN62", type = "button-position", hardwareLabel = "Button 62 — JMR OFF" },
    { id = "viper-tqs-button-63", key = "JOY_BTN63", type = "button-position", hardwareLabel = "Button 63 — AP ROLL ATT HOLD" },
    { id = "viper-tqs-button-64", key = "JOY_BTN64", type = "button-position", hardwareLabel = "Button 64 — AP PITCH OFF" },
    { id = "viper-tqs-axis-x", key = "JOY_X", type = "axis", hardwareLabel = "Axis X — RDR CURSOR X" },
    { id = "viper-tqs-axis-y", key = "JOY_Y", type = "axis", hardwareLabel = "Axis Y — RDR CURSOR Y" },
    { id = "viper-tqs-axis-z", key = "JOY_Z", type = "axis", hardwareLabel = "Axis Z — THROTTLE" },
    { id = "viper-tqs-axis-rx", key = "JOY_RX", type = "axis", hardwareLabel = "Axis RX — MAN RNG" },
    { id = "viper-tqs-axis-ry", key = "JOY_RY", type = "axis", hardwareLabel = "Axis RY — ANT ELEV" },
    { id = "viper-tqs-axis-rz", key = "JOY_RZ", type = "axis", hardwareLabel = "Axis RZ — ZOOM VIEW" },
  },
}
