return {
  schemaVersion = 1,
  id = "winctrl-icp",
  name = "WINCTRL ViperAce ICP",
  controls = {
    { id = "winctrl-icp-btn-01", key = "JOY_BTN1", type = "button", hardwareLabel = "COM 1" },
    { id = "winctrl-icp-btn-02", key = "JOY_BTN2", type = "button", hardwareLabel = "COM 2" },
    { id = "winctrl-icp-btn-03", key = "JOY_BTN3", type = "button", hardwareLabel = "IFF" },
    { id = "winctrl-icp-btn-04", key = "JOY_BTN4", type = "button", hardwareLabel = "LIST" },
    { id = "winctrl-icp-btn-05", key = "JOY_BTN5", type = "button", hardwareLabel = "A-A" },
    { id = "winctrl-icp-btn-06", key = "JOY_BTN6", type = "button", hardwareLabel = "A-G" },
    { id = "winctrl-icp-btn-07", key = "JOY_BTN7", type = "button", hardwareLabel = "ICP key 1" },
    { id = "winctrl-icp-btn-08", key = "JOY_BTN8", type = "button", hardwareLabel = "ICP key 2" },
    { id = "winctrl-icp-btn-09", key = "JOY_BTN9", type = "button", hardwareLabel = "ICP key 3" },
    { id = "winctrl-icp-btn-10", key = "JOY_BTN10", type = "button", hardwareLabel = "ICP key 4" },
    { id = "winctrl-icp-btn-11", key = "JOY_BTN11", type = "button", hardwareLabel = "ICP key 5" },
    { id = "winctrl-icp-btn-12", key = "JOY_BTN12", type = "button", hardwareLabel = "ICP key 6" },
    { id = "winctrl-icp-btn-13", key = "JOY_BTN13", type = "button", hardwareLabel = "ICP key 7" },
    { id = "winctrl-icp-btn-14", key = "JOY_BTN14", type = "button", hardwareLabel = "ICP key 8" },
    { id = "winctrl-icp-btn-15", key = "JOY_BTN15", type = "button", hardwareLabel = "ICP key 9" },
    { id = "winctrl-icp-btn-16", key = "JOY_BTN16", type = "button", hardwareLabel = "ICP key 0" },
    { id = "winctrl-icp-btn-17", key = "JOY_BTN17", type = "button", hardwareLabel = "RCL" },
    { id = "winctrl-icp-btn-18", key = "JOY_BTN18", type = "button", hardwareLabel = "ENTR" },
    { id = "winctrl-icp-btn-19", key = "JOY_BTN19", type = "button", hardwareLabel = "C/P/BRT rocker up" },
    { id = "winctrl-icp-btn-20", key = "JOY_BTN20", type = "button", hardwareLabel = "C/P/BRT rocker down" },
    { id = "winctrl-icp-btn-21", key = "JOY_BTN21", type = "button", hardwareLabel = "RTN/SEQ press" },
    { id = "winctrl-icp-btn-22", key = "JOY_BTN22", type = "button", hardwareLabel = "RTN/SEQ up" },
    { id = "winctrl-icp-btn-23", key = "JOY_BTN23", type = "button", hardwareLabel = "RTN/SEQ right" },
    { id = "winctrl-icp-btn-24", key = "JOY_BTN24", type = "button", hardwareLabel = "RTN/SEQ down" },
    { id = "winctrl-icp-btn-25", key = "JOY_BTN25", type = "button", hardwareLabel = "RTN/SEQ left" },
    { id = "winctrl-icp-btn-26", key = "JOY_BTN26", type = "button", hardwareLabel = "DRIFT C/O" },
    { id = "winctrl-icp-btn-27", key = "JOY_BTN27", type = "button", hardwareLabel = "NORM" },
    { id = "winctrl-icp-btn-28", key = "JOY_BTN28", type = "button", hardwareLabel = "WARN RESET" },
    { id = "winctrl-icp-btn-29", key = "JOY_BTN29", type = "button", hardwareLabel = "FLIR rocker up" },
    { id = "winctrl-icp-btn-30", key = "JOY_BTN30", type = "button", hardwareLabel = "FLIR rocker press" },
    { id = "winctrl-icp-btn-31", key = "JOY_BTN31", type = "button", hardwareLabel = "FLIR rocker down" },
    { id = "winctrl-icp-btn-32", key = "JOY_BTN32", type = "button", hardwareLabel = "GAIN rocker up" },
    { id = "winctrl-icp-btn-33", key = "JOY_BTN33", type = "button", hardwareLabel = "GAIN rocker press" },
    { id = "winctrl-icp-btn-34", key = "JOY_BTN34", type = "button", hardwareLabel = "GAIN rocker down" },
    { id = "winctrl-icp-axis-y", key = "JOY_Y", type = "axis", hardwareLabel = "left upper wheel" },
    { id = "winctrl-icp-axis-x", key = "JOY_X", type = "axis", hardwareLabel = "right upper wheel" },
    { id = "winctrl-icp-axis-ry", key = "JOY_RY", type = "axis", hardwareLabel = "left lower wheel" },
    { id = "winctrl-icp-axis-rx", key = "JOY_RX", type = "axis", hardwareLabel = "right lower wheel" },
  },
}
