return {
  schemaVersion = 1,
  id = "winctrl-pto2",
  name = "WINCTRL PTO2",
  controls = {
    { id = "pto2-button-1", key = "JOY_BTN1", type = "button", hardwareLabel = "Lower-left panel pushbutton" },
    { id = "pto2-button-2", key = "JOY_BTN2", type = "button", hardwareLabel = "Master caution pushbutton" },
    { id = "pto2-button-3", key = "JOY_BTN3", type = "switch-position", hardwareLabel = "Launch bar retract" },
    { id = "pto2-button-4", key = "JOY_BTN4", type = "switch-position", hardwareLabel = "Launch bar extend" },
    { id = "pto2-button-5", key = "JOY_BTN5", type = "switch-position", hardwareLabel = "Flaps upper position" },
    { id = "pto2-button-6", key = "JOY_BTN6", type = "switch-position", hardwareLabel = "Flaps auto" },
    { id = "pto2-button-7", key = "JOY_BTN7", type = "switch-position", hardwareLabel = "Flaps full" },
    { id = "pto2-button-8", key = "JOY_BTN8", type = "switch-position", hardwareLabel = "Landing gear upper auxiliary input" },
    { id = "pto2-button-9", key = "JOY_BTN9", type = "switch-position", hardwareLabel = "Landing gear lower auxiliary input" },
    { id = "pto2-button-10", key = "JOY_BTN10", type = "switch-position", hardwareLabel = "Probe extend" },
    { id = "pto2-button-11", key = "JOY_BTN11", type = "switch-position", hardwareLabel = "Probe retract" },
    { id = "pto2-button-12", key = "JOY_BTN12", type = "switch-position", hardwareLabel = "Hook bypass field" },
    { id = "pto2-button-13", key = "JOY_BTN13", type = "switch-position", hardwareLabel = "Hook bypass carrier" },
    { id = "pto2-button-14", key = "JOY_BTN14", type = "switch-position", hardwareLabel = "Emergency jettison upper position" },
    { id = "pto2-button-15", key = "JOY_BTN15", type = "switch-position", hardwareLabel = "Emergency jettison center position" },
    { id = "pto2-button-16", key = "JOY_BTN16", type = "switch-position", hardwareLabel = "Emergency jettison lower position" },
    { id = "pto2-button-17", key = "JOY_BTN17", type = "rotary-position", hardwareLabel = "Select jettison L FUS / MSL" },
    { id = "pto2-button-18", key = "JOY_BTN18", type = "rotary-position", hardwareLabel = "Select jettison SAFE" },
    { id = "pto2-button-19", key = "JOY_BTN19", type = "rotary-position", hardwareLabel = "Select jettison R FUS / MSL" },
    { id = "pto2-button-20", key = "JOY_BTN20", type = "rotary-position", hardwareLabel = "Select jettison RACK / LCHR" },
    { id = "pto2-button-21", key = "JOY_BTN21", type = "rotary-position", hardwareLabel = "Select jettison STORES" },
    { id = "pto2-button-22", key = "JOY_BTN22", type = "button", hardwareLabel = "Select jettison pushbutton" },
    { id = "pto2-button-23", key = "JOY_BTN23", type = "button", hardwareLabel = "Jet station select center" },
    { id = "pto2-button-24", key = "JOY_BTN24", type = "button", hardwareLabel = "Jet station select LI" },
    { id = "pto2-button-25", key = "JOY_BTN25", type = "button", hardwareLabel = "Jet station select RI" },
    { id = "pto2-button-26", key = "JOY_BTN26", type = "button", hardwareLabel = "Jet station select LO" },
    { id = "pto2-button-27", key = "JOY_BTN27", type = "button", hardwareLabel = "Jet station select RO" },
    { id = "pto2-button-28", key = "JOY_BTN28", type = "switch-position", hardwareLabel = "Wings fold" },
    { id = "pto2-button-29", key = "JOY_BTN29", type = "switch-position", hardwareLabel = "Wings hold" },
    { id = "pto2-button-30", key = "JOY_BTN30", type = "switch-position", hardwareLabel = "Wings spread" },
    { id = "pto2-button-31", key = "JOY_BTN31", type = "switch-position", hardwareLabel = "Wings lock/unlock" },
    { id = "pto2-button-32", key = "JOY_BTN32", type = "switch-position", hardwareLabel = "Hook handle upper position" },
    { id = "pto2-button-33", key = "JOY_BTN33", type = "switch-position", hardwareLabel = "Hook handle center position" },
    { id = "pto2-button-34", key = "JOY_BTN34", type = "switch-position", hardwareLabel = "Hook handle lower position" },
    { id = "pto2-button-35", key = "JOY_BTN35", type = "switch-position", hardwareLabel = "Landing gear handle up" },
    { id = "pto2-button-36", key = "JOY_BTN36", type = "switch-position", hardwareLabel = "Landing gear handle center" },
    { id = "pto2-button-37", key = "JOY_BTN37", type = "switch-position", hardwareLabel = "Landing gear handle down" },
    { id = "pto2-button-38", key = "JOY_BTN38", type = "switch-position", hardwareLabel = "Emergency brake / parking brake position 1" },
    { id = "pto2-button-39", key = "JOY_BTN39", type = "switch-position", hardwareLabel = "Emergency brake / parking brake position 2" },
    { id = "pto2-button-40", key = "JOY_BTN40", type = "switch-position", hardwareLabel = "Emergency brake / parking brake position 3" },
    { id = "pto2-button-41", key = "JOY_BTN41", type = "switch-position", hardwareLabel = "Emergency brake / parking brake position 4" },
  },
}
