using System.Globalization;
using System.IO;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using DcsConsumerScaffold.Models;

namespace DcsConsumerScaffold.Services;

public sealed class DcsHtmlCommandCatalogResult
{
    public required DcsCommandCatalogDocument Document { get; init; }
    public int FileCount { get; init; }
    public int EffectiveAssignmentCount { get; init; }
    public int DuplicateCommandCount { get; init; }
}

public sealed partial class DcsHtmlCommandCatalogProvider
{
    public DcsHtmlCommandCatalogResult Build(IEnumerable<string> htmlPaths, string moduleId)
    {
        if (string.IsNullOrWhiteSpace(moduleId))
            throw new ArgumentException("Load a module preview with an input module ID before importing DCS HTML.", nameof(moduleId));

        var paths = htmlPaths?.Where(path => !string.IsNullOrWhiteSpace(path))
            .Select(Path.GetFullPath)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase)
            .ThenBy(path => path, StringComparer.OrdinalIgnoreCase)
            .ToList() ?? [];
        if (paths.Count == 0) throw new InvalidDataException("Select one or more HTML files generated by DCS Controls.");

        var commands = new Dictionary<string, DcsCommandCatalogEntry>(StringComparer.Ordinal);
        var sources = new List<DcsCommandCatalogSourceFile>();
        var fingerprintInput = new StringBuilder();
        var effectiveAssignments = 0;
        var duplicateCommands = 0;

        foreach (var path in paths)
        {
            if (!File.Exists(path)) throw new FileNotFoundException("DCS Controls HTML export was not found.", path);
            if (!string.Equals(Path.GetExtension(path), ".html", StringComparison.OrdinalIgnoreCase) &&
                !string.Equals(Path.GetExtension(path), ".htm", StringComparison.OrdinalIgnoreCase))
                throw new InvalidDataException($"'{Path.GetFileName(path)}' is not an HTML file generated by DCS Controls.");

            var content = File.ReadAllText(path);
            var device = ParseDevice(content, path);
            var sourceHash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(content))).ToLowerInvariant();
            sources.Add(new DcsCommandCatalogSourceFile { Device = device, File = Path.GetFileName(path), Sha256 = sourceHash });
            fingerprintInput.Append(Path.GetFileName(path).ToLowerInvariant()).Append(':').Append(sourceHash).Append('\n');

            var rows = ParseRows(content, path);
            var fileKeys = new HashSet<string>(StringComparer.Ordinal);
            foreach (var row in rows)
            {
                if (!fileKeys.Add(row.BindingKey))
                    throw new InvalidDataException($"{Path.GetFileName(path)} row {row.RowNumber}: duplicate command hash '{row.BindingKey}'.");

                if (!commands.TryGetValue(row.BindingKey, out var command))
                {
                    command = new DcsCommandCatalogEntry
                    {
                        BindingKey = row.BindingKey,
                        Name = row.Name,
                        RawName = row.Name,
                        CategoryPath = row.Category.Split(';', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries).ToList(),
                        Type = row.BindingKey.StartsWith('a') ? "axis" : "button",
                        Actions = DecodeActions(row.BindingKey),
                        Source = new DcsCommandSource { Provider = "dcs-controls-html-export", File = "DCS Generate HTML" },
                        IsAssignable = true,
                    };
                    commands.Add(row.BindingKey, command);
                }
                else
                {
                    duplicateCommands += 1;
                    var category = string.Join("; ", command.CategoryPath);
                    if (!string.Equals(command.Name, row.Name, StringComparison.Ordinal) ||
                        !string.Equals(category, row.Category, StringComparison.Ordinal))
                        throw new InvalidDataException(
                            $"{Path.GetFileName(path)} row {row.RowNumber}: command hash '{row.BindingKey}' has metadata " +
                            $"'{row.Name}' / '{row.Category}', but an earlier export has '{command.Name}' / '{category}'.");
                }

                foreach (var combo in row.Combos.Split(';', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries))
                {
                    command.CurrentAssignments.Add(new DcsCommandCurrentAssignment { Device = device, Combo = combo });
                    effectiveAssignments += 1;
                }
            }
        }

        foreach (var command in commands.Values)
            command.CurrentAssignments = command.CurrentAssignments
                .OrderBy(assignment => assignment.Device, StringComparer.OrdinalIgnoreCase)
                .ThenBy(assignment => assignment.Combo, StringComparer.Ordinal)
                .ToList();

        var fingerprint = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(fingerprintInput.ToString()))).ToLowerInvariant();
        return new DcsHtmlCommandCatalogResult
        {
            FileCount = paths.Count,
            EffectiveAssignmentCount = effectiveAssignments,
            DuplicateCommandCount = duplicateCommands,
            Document = new DcsCommandCatalogDocument
            {
                SchemaVersion = 1,
                ModuleId = moduleId.Trim(),
                Locale = "en",
                DcsVersion = null,
                GeneratedAt = DateTimeOffset.UtcNow,
                SourceFingerprint = fingerprint,
                SourceFiles = sources,
                Commands = commands.Values
                    .OrderBy(command => command.Category, StringComparer.OrdinalIgnoreCase)
                    .ThenBy(command => command.Name, StringComparer.OrdinalIgnoreCase)
                    .ThenBy(command => command.BindingKey, StringComparer.Ordinal)
                    .ToList(),
            },
        };
    }

    private static string ParseDevice(string content, string path)
    {
        var heading = H1Regex().Match(content);
        if (!heading.Success) throw new InvalidDataException($"{Path.GetFileName(path)}: missing DCS device h1 heading.");
        var device = Clean(heading.Groups[1].Value);
        if (string.IsNullOrWhiteSpace(device)) throw new InvalidDataException($"{Path.GetFileName(path)}: empty DCS device heading.");
        var fileStem = Path.GetFileNameWithoutExtension(path);
        if (!string.Equals(device, fileStem, StringComparison.OrdinalIgnoreCase))
            throw new InvalidDataException($"{Path.GetFileName(path)}: device heading '{device}' does not match filename '{fileStem}'.");
        return device;
    }

    private static List<HtmlRow> ParseRows(string content, string path)
    {
        var result = new List<HtmlRow>();
        var rowNumber = 0;
        foreach (Match rowMatch in RowRegex().Matches(content))
        {
            var cells = CellRegex().Matches(rowMatch.Groups[1].Value).Cast<Match>()
                .Select(match => Clean(match.Groups[1].Value)).ToList();
            if (cells.Count == 0) continue;
            rowNumber += 1;
            if (cells.Count != 4)
                throw new InvalidDataException($"{Path.GetFileName(path)} row {rowNumber}: expected four DCS columns, found {cells.Count}.");
            var bindingKey = cells[3].Trim();
            if (string.IsNullOrWhiteSpace(cells[1]) || string.IsNullOrWhiteSpace(bindingKey))
                throw new InvalidDataException($"{Path.GetFileName(path)} row {rowNumber}: command name and hash are required.");
            if (!AxisHashRegex().IsMatch(bindingKey) && !ButtonHashRegex().IsMatch(bindingKey))
                throw new InvalidDataException($"{Path.GetFileName(path)} row {rowNumber}: unsupported command hash '{bindingKey}'.");
            result.Add(new HtmlRow(rowNumber, cells[0], cells[1], cells[2], bindingKey));
        }
        if (result.Count == 0) throw new InvalidDataException($"{Path.GetFileName(path)} contains no DCS command rows.");
        return result;
    }

    private static string Clean(string html)
    {
        var value = WebUtility.HtmlDecode(TagRegex().Replace(
                BreakRegex().Replace(html, " "), string.Empty))
            .Replace('\u00a0', ' ')
            .Trim();
        return WhitespaceRegex().Replace(value, " ");
    }

    private static DcsCommandActions DecodeActions(string bindingKey)
    {
        var actions = new DcsCommandActions();
        if (bindingKey.StartsWith('a')) return actions;
        var match = ButtonPartsRegex().Match(bindingKey);
        if (!match.Success) return actions;
        actions.Down = Integer(match.Groups[1].Value);
        actions.Pressed = Integer(match.Groups[2].Value);
        actions.Up = Integer(match.Groups[3].Value);
        actions.CockpitDeviceId = Integer(match.Groups[4].Value);
        actions.ValueDown = Number(match.Groups[5].Value);
        actions.ValuePressed = Number(match.Groups[6].Value);
        actions.ValueUp = Number(match.Groups[7].Value);
        return actions;
    }

    private static int? Integer(string value) => value == "nil" ? null :
        int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var result) ? result : null;
    private static double? Number(string value) => value == "nil" ? null :
        double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out var result) ? result : null;

    private sealed record HtmlRow(int RowNumber, string Combos, string Name, string Category, string BindingKey);

    [GeneratedRegex("<h1[^>]*>([\\s\\S]*?)</h1>", RegexOptions.IgnoreCase)] private static partial Regex H1Regex();
    [GeneratedRegex("<tr[^>]*>([\\s\\S]*?)</tr>", RegexOptions.IgnoreCase)] private static partial Regex RowRegex();
    [GeneratedRegex("<td[^>]*>([\\s\\S]*?)</td>", RegexOptions.IgnoreCase)] private static partial Regex CellRegex();
    [GeneratedRegex("<[^>]+>")] private static partial Regex TagRegex();
    [GeneratedRegex("<br\\s*/?>", RegexOptions.IgnoreCase)] private static partial Regex BreakRegex();
    [GeneratedRegex("\\s+")] private static partial Regex WhitespaceRegex();
    [GeneratedRegex("^a.+cd(?:nil|-?\\d+)$")] private static partial Regex AxisHashRegex();
    [GeneratedRegex("^d.+p.+u.+cd.+vd.+vp.+vu.+$")] private static partial Regex ButtonHashRegex();
    [GeneratedRegex("^d(.+?)p(.+?)u(.+?)cd(.+?)vd(.+?)vp(.+?)vu(.+)$")] private static partial Regex ButtonPartsRegex();
}
